### ISSUE TITLE
Script and website /_ ! _\

### ISSUE THREAD

**Issue by Fabian68** [Adrianotiger/desktopPet#15] opened 2017-05-27 21:14 UTC
Your website can't charge and you script e-sheep is not working anymore , this is the problem i think , i hope a fixe , then i can use it again , thx and sorry for my english .

**Comment by Adrianotiger** [comment] 2017-05-28 07:51
Hi Fabian.
Sorry I am not able to reproduce it. It is working on my browser.
There are different possibilities for this behaviour:
- popupblocker
- you are using this script inside a https (in this case you have to copy the script locally to your webpage)
- some browser bugs

**Comment by Fabian68** [comment] 2017-05-28 09:59
I am not using popupblocker and not using in https , i can't load ur webpage http://esheep.petrucci.ch/ and i can't load page with the e-sheep script , i am using chrome :$ 
Thank you for your answer .

**Comment by RedSparr0w** [comment] 2017-05-28 22:54
I am getting the same problem using `Chrome 58.0.3029.110 (64-bit)`

From some testing it appears to be caused by the `DesktopPet_beta.js` script,
As soon as you try load a pet in the browser it will cause the tab to "freeze".

You should be able to test this on http://esheep.petrucci.ch/script/pettester.php,
Once you click a pet the page will no longer respond.

**Comment by Adrianotiger** [comment] 2017-05-29 09:59
I see it. But it seems more a browser bug than a script error. Ok, the script is not clean and should use some more events to load everything, but the script never changed over 1 year...

I changed the script a little bit, instead of wait until the image is loaded, I will load a 1x1 px dynamically and then load the pet. It works on Vivaldi (use Chromium) at least. But I am asking me why Chrome is not able to load a png from a base64 string now!

**Comment by Fabian68** [comment] 2017-05-29 16:31
Hmm it's probably Chrome fault when they update :/

**Comment by RedSparr0w** [comment] 2017-05-29 23:53
Yeah has to be something to do with the latest versions of chrome.
Still does not work properly for me though.

It creates the object but it stays as
```css
{
  width: 0px;
  height: 0px;
}
```

but at least it doesn't freeze now.
😄

**Comment by RedSparr0w** [comment] 2017-07-12 05:42
Firgured out how to fix the problem
Need to change the following:
```javascript
    this.sprite.src = 'data:image/png;base64,' + image.getElementsByTagName("png")[0].textContent;
    this.DOMimg.setAttribute("src", this.sprite.src);
    var attribute = 
      "width:" + (this.sprite.width) + "px;" +
      "height:" + (this.sprite.height) + "px;" +
      "position:absolute;" + 
      "top:0px;" + 
      "left:0px;";
    this.DOMimg.setAttribute("style", attribute);
    this.DOMimg.ondragstart = function() { return false; };
    this.imageW = this.sprite.width / this.tilesX;
    this.imageH = this.sprite.height / this.tilesY;
    this.imageX = 0;
    this.imageY = this.screenH - this.sprite.height / this.tilesY;
    for(var i=0;i<5000;i++) if(this.sprite.width != 0) break;
    attribute = 
      "width:" + (this.imageW) + "px;" +
      "height:" + (this.imageH) + "px;" +
      "position:fixed;" + 
      "top:" + (this.imageY) + "px;" + 
      "left:" + (this.imageX) + "px;" + 
      "transform:rotatey(0deg);" +
      "cursor:move;" +
      "z-index:2000;" +
      "overflow:hidden;"; 
    this.DOMdiv.setAttribute("style", attribute);
    this.DOMdiv.appendChild(this.DOMimg);
```
Looks like its settings the height + width before it can load the image properly

The below seems to work fine even though it's only a 1ms delay, just gives it enough time to process.
```javascript
    this.sprite.src = 'data:image/png;base64,' + image.getElementsByTagName("png")[0].textContent;
    this.DOMimg.setAttribute("src", this.sprite.src);
    setTimeout(function(){
      var attribute = 
        "width:" + (_esheep.sprite.width) + "px;" +
        "height:" + (_esheep.sprite.height) + "px;" +
        "position:absolute;" + 
        "top:0px;" + 
        "left:0px;";
      _esheep.DOMimg.setAttribute("style", attribute);
      _esheep.DOMimg.ondragstart = function() { return false; };
      _esheep.imageW = _esheep.sprite.width / _esheep.tilesX;
      _esheep.imageH = _esheep.sprite.height / _esheep.tilesY;
      _esheep.imageX = 0;
      _esheep.imageY = _esheep.screenH - _esheep.sprite.height / _esheep.tilesY;
      attribute = 
        "width:" + (_esheep.imageW) + "px;" +
        "height:" + (_esheep.imageH) + "px;" +
        "position:fixed;" + 
        "top:" + (_esheep.imageY) + "px;" + 
        "left:" + (_esheep.imageX) + "px;" + 
        "transform:rotatey(0deg);" +
        "cursor:move;" +
        "z-index:2000;" +
        "overflow:hidden;"; 
      _esheep.DOMdiv.setAttribute("style", attribute);
      _esheep.DOMdiv.appendChild(_esheep.DOMimg);
    }, 1);
```

**Comment by Adrianotiger** [comment] 2017-07-12 13:31
I modified the script with your code (with the onload event instead of the timeout).
Can you try it to see if it works now?

**Comment by Fabian68** [comment] 2017-07-12 13:57
It actually working on your website :p

**Comment by RedSparr0w** [comment] 2017-07-13 00:36
Nice, All working now.

Only thing that doesn't seem to work is any "children".

But its not really a big deal.

**Comment by Adrianotiger** [comment] 2017-07-13 11:44
Fantastic :) So I can close this issue.
Children are not implemented yet.

I wasn't thinking that this web-project could so important :P hehehe

I will open a new GitHub project for it. So new animations/pets can be uploaded in the github without using my online generator. But for this I need to work on my JavaScript code as it was a 1-day project :P

**Closed by Adrianotiger** 2017-07-13 11:44 UTC
